### PR TITLE
Cannot enter a precise number starting with a decimal

### PR DESCRIPTION
**Pull request by CBft9MFGIb0Xd**
Able to get value from ".5"
https://issues.openmrs.org/browse/HTML-474

### CODE REVIEW

**Comment by mogoodrich** [comment]
Please see the previous ticket:

https://issues.openmrs.org/browse/HTML-436

Although the Number(x) that you use is stricter than parseInt and parseFloat and will return NaN for "123xab", I still don't think it is as strict as we want it to be--for instance, it appears that Number("") = 0.

I think the least invasive change that would not have unintentional side effects would be to change the regex:

/^[+-]?\d+(\.\d+)?$/

to:

/^[+-]?\d*(\.\d+)?$/

**Comment by mogoodrich** [comment]
@CBft9MFGIb0Xd do you have an account on OpenMRS Jira?  If so, I can assign this ticket to you (if you plan to continue work on it).

Thanks!

**Comment by CBft9MFGIb0Xd** [comment]
@mogoodrich I'm trying to sign up on OpenMRS Jira but the signup system seems to be broken.

**Comment by psbrandt** [comment]
@CBft9MFGIb0Xd send a mail to [helpdesk@openmrs.org](mailto:helpdesk@openmrs.org) describing your issue and they will be able to help you get an account.

**Comment by dkayiwa** [comment]
@CBft9MFGIb0Xd did you succeed on the above?

**Comment by CBft9MFGIb0Xd** [comment]
@dkayiwa yes I made new changes. It can be merged

**Comment by mogoodrich** [comment]
Thanks @CBft9MFGIb0Xd, I merged it in!  Did you ever get a Jira account so I can properly add you to the ticket?

**Comment by CBft9MFGIb0Xd** [comment]
@mogoodrich I do have a Jira account my username is snlkasvn113

**Pull request merged**
