### PR TITLE
Updates on DrugCompatibility 2.0

### PR DESCRIPTION
**Pull request by sherrif10**
Am proposing of whether we can modify this code by adding the the Drug expiry date in order to encapsulate the  whole code. j thought it would make some good change and functionality. Especially in line 40 . more light on this idea will be highly appreciated  whether it makes sense or not. @dkayiwa some comments and improvements.thanks

## Issue I worked on

see https://issues.openmrs.org/browse/HTML-

## Checklist: I completed these to help reviewers :)

- [ ] My pull request only contains **ONE single commit**
(the number above, next to the 'Commits' tab is 1).

  No? -> [read here](https://wiki.openmrs.org/display/docs/Pull+Request+Tips) on how to squash multiple commits into one

- [ ] My IDE is configured to follow the [**code style**](https://wiki.openmrs.org/display/docs/Java+Conventions) of this project.

  No? Unsure? -> [configure your IDE](https://wiki.openmrs.org/display/docs/How-To+Setup+And+Use+Your+IDE), format the code and add the changes with `git add . && git commit --amend`

- [ ] I have **added tests** to cover my changes. (If you refactored
  existing code that was well tested you do not have to add tests)

  No? -> write tests and add them to this commit `git add . && git commit --amend`

- [ ] I ran `mvn clean package` right before creating this pull request and
  added all formatting changes to my commit.

  No? -> execute above command

- [ ] All new and existing **tests passed**.

  No? -> figure out why and add the fix to your commit. It is your responsibility to make sure your code works.

- [ ] My pull request is **based on the latest changes** of the master branch.

  No? Unsure? -> execute command `git pull --rebase upstream master`

### CODE REVIEW

**Comment by dkayiwa** [comment]
Can you take a look at this? https://wiki.openmrs.org/display/docs/Pull+Request+Tips

**Comment by sherrif10** [comment]
Ok thanks, let me have a look at it

**Comment by mogoodrich** [comment]
In particular @sherrif10  can you create a ticket in JIRA explaining what you intent to do (in the HTML Form Entry project)? Then, once we agree, the commit should have the ticket number in the commit message.

**Comment by sherrif10** [comment]
ok thank j will create it such that we can have more discussion about it especially @daniel kayiwa, @mogoodrich , @k-joseph ,@mozzy

**Comment by dkayiwa** [comment]
@sherrif10 are you still working on this?

**Comment by sherrif10** [comment]
Am nolonger working on this please, this is old code, though iam closing it for meanwhile i will come along

**Pull request closed without merging**
