### PR TITLE
fixed HTML-573

### PR DESCRIPTION
**Pull request by piyush9620**
fixed issue https://issues.openmrs.org/browse/HTML-573

### CODE REVIEW

**Comment by piyush9620** [comment]
screen shot 2018-03-09 at 11 23 07 am

I tried checking, it seems to work. Here is an image from a form in french.

**Comment by piyush9620** [comment]
There is also an existing instance of messages being fetched via jquery, at https://github.com/piyush9620/openmrs-module-htmlformentry/blob/25632838bac83a333ad732b9dd91d6299e5f117c/omod/src/main/webapp/resources/htmlFormEntry.js#L529
in the same file.

**Comment by mogoodrich** [comment]
Great, thanks @piyush9620 !

**Comment by mogoodrich** [comment]
Great, thanks @piyush9620 !

**Pull request merged**
