### PR TITLE
HTML-689: Add stateLabelCode and stateLabelCodes to workflowState htm…

### PR DESCRIPTION
**Pull request by ODORA0**
…lform tag

**Issue worked on:** https://issues.openmrs.org/browse/HTML-689

### CODE REVIEW

**Comment by ODORA0** [comment]
This is still a work in progress though adding `stateIds="0,6,8"` causes this build failure both locally and on Travis. Any guidance on this

**Comment by dkayiwa** [comment]
Did you ask on talk?

**Comment by ODORA0** [comment]
Been able to deal with the error, any reviews on this?

**Comment by mogoodrich** [comment]
@ODORA0 the only changed file I see currently in this PR is the test form?

**Comment by ODORA0** [comment]
Any reviews?

**Comment by mogoodrich** [comment]
@ODORA0 see my comment above? I think there are more changes than when I last took a look, but it still looks like only test forms have been changed?

**Comment by ODORA0** [comment]
@mogoodrich Correct me if am wrong but as far as I understand the ticket requirements is that labels for workFlowState [stateLabel(s)] should be added within the htmlform tags, which I think I have done

**Pull request closed without merging**
