### PR TITLE
HTML-754: NumberFieldWidget does not throw validation exception if va…

### PR DESCRIPTION
**Pull request by mogoodrich**
…lue is has decimal component and isFloat=false

## Issue I worked on

see https://issues.openmrs.org/browse/HTML-

## Checklist: I completed these to help reviewers :)

- [ ] My pull request only contains **ONE single commit**
(the number above, next to the 'Commits' tab is 1).

  No? -> [read here](https://wiki.openmrs.org/display/docs/Pull+Request+Tips) on how to squash multiple commits into one

- [ ] My IDE is configured to follow the [**code style**](https://wiki.openmrs.org/display/docs/Java+Conventions) of this project.

  No? Unsure? -> [configure your IDE](https://wiki.openmrs.org/display/docs/How-To+Setup+And+Use+Your+IDE), format the code and add the changes with `git add . && git commit --amend`

- [ ] I have **added tests** to cover my changes. (If you refactored
  existing code that was well tested you do not have to add tests)

  No? -> write tests and add them to this commit `git add . && git commit --amend`

- [ ] I ran `mvn clean package` right before creating this pull request and
  added all formatting changes to my commit.

  No? -> execute above command

- [ ] All new and existing **tests passed**.

  No? -> figure out why and add the fix to your commit. It is your responsibility to make sure your code works.

- [ ] My pull request is **based on the latest changes** of the master branch.

  No? Unsure? -> execute command `git pull --rebase upstream master`

### CODE REVIEW

**Review by brandones — APPROVED** [review]

**Review by mseaton — COMMENTED** [review]
FYI - I've made (in my in progress branch) some related changes to the NumberFieldWidget that might lead to a slightly different solution.  

What I think we should do is:

a) Change the return type of the getValue method to be a "Number".
b) Instead of parsing to a Double, parse to either an Integer or a Double depending on the value of floatingPoint true/false.
c) In the catch block for NumberFormatException, change the message based on whether floating point is true/false to say "Not a valid integer" or "Not a valid number" depending.

This will solve this issue, and also has tangential benefits that the returned value accurately reflects what was actually collected and intended by the widget.

**Comment by mogoodrich** [comment]
@mseaton  that works for me... are you currently working on that as part of your commit, or should I work on this?

**Comment by mseaton** [comment]
If you could just bang it in, that would be better.  My branch is interminable and would need to resolve conflicts here.  I'd rather just revert my change and merge up from master to get this, if possible

**Comment by mogoodrich** [comment]
Got it, will do...

**Comment by mogoodrich** [comment]
Unfortunately, changing the method signature from Double to Number leads to compile issues with the DrugOrderElement... :)  Since this is what you are working on, doesn't seem to make much sense for me to dive into this?

**Comment by mseaton** [comment]
I'm not really working on that, and that should be trivial to fix, and actually that is probably what needed the fix when I initially threw it together.  The issue is that some DrugOrder properties are Integers (quantity, numRefills).  Whatever compilation errors you are seeing should be trivial to fix.  Probably just need "setInitialValue" to take in a Number rather than a Double, and to make sure when this widget is used it is cast to either Number or to Integer/Double appropriately.

**Comment by mogoodrich** [comment]
I could dig into it tomorrow, but, no matter how trivial, it just seems silly for me to spend any time making changes to DrugOrderSubmissionElement (where the compile errors are) at this point since you are refactoring it?

**Comment by mseaton** [comment]
I don't have changes to DrugOrderSubmissionElement - I'm creating a new tag.  I did identify the changes that I think should be needed to it (these are the only changes I have to DrugOrderSubmissionElement in my branch, which are all due to the changes I initially made to the NumberFieldWidget as described above):

1. Cast quantity to a Double:
`		orderTag.quantity = (Double) quantityWidget.getValue(session.getContext(), submission);
`
2. Cast duration to an Integer (can get rid of the null check)
`		orderTag.duration = (Integer) durationWidget.getValue(session.getContext(), submission);
`
3. Cast numRefills to an Integer (can get rid of the null check)
`		orderTag.numRefills = (Integer) numRefillsWidget.getValue(session.getContext(), submission);
`

**Comment by mogoodrich** [comment]
After sleeping on this, I'm going to merge this in as-is... although the risk seems relatively low, the risk of refactoring and introducing method signature changes seems unnecessary just for the needs of this ticket (add a validation message)... definitely happy to consider refactoring as part of the overall Drug rework.

**Pull request merged**
