### PR TITLE
HTML-733: ComplexData's data to enforce ByteArrayInputStream.

### PR DESCRIPTION
**Pull request by gitcliff**
https://issues.openmrs.org/browse/HTML-733

### CODE REVIEW

**Comment by gitcliff** [comment]
thanks @mks-d for the review ,,,its cool to change this into a draft and do i have to wait for the improved mechanism of setting file parameters to be implemented first?

**Comment by mks-d** [comment]
@gitcliff I intended to do it as part of the PR for this ticket. I haven't looked into it yet, so I wasn't sure yet about how I'd do that. Feel free to try if you don't have any other tickets to work on.

**Comment by gitcliff** [comment]
@mks-d am abit caught up with some community priority tickets but am going to keep looking deeper into this.

**Comment by mogoodrich** [comment]
Will hold off reviewing for now (honestly, I keep forgetting exactly how all this complex stuff works... :) ) but feel free to ping me if there's something you want me to look at.

**Comment by mks-d** [comment]
Closing this because of this new PR: https://github.com/openmrs/openmrs-module-htmlformentry/pull/184

**Pull request closed without merging**
