### PR TITLE
HTML- 329  add a drugOrder attribute to hide only dose, not frequency

### PR DESCRIPTION
**Pull request by dilekamadushan**
Modified DrugOrderSubmissionElement.java accordingly

### CODE REVIEW

**Comment by dilekamadushan** [comment]
@mogoodrich Feel free to check on this. Thanks

**Comment by mogoodrich** [comment]
Thanks @dilekamadushan !  Can you provide a quick screenshot just to verify that this working correctly?

**Comment by dilekamadushan** [comment]
@mogoodrich I will work on it.

**Comment by dilekamadushan** [comment]
@mogoodrich I tried to add the following in html Form.
<drugOrder drugNames="RIF 300,RHEZ,PZA 500,/Syrups/,NVP Susp" drugLabels="RIF,RZ, PZ, NVP Syrup"  hideDoseAndFrequency="true"/>
But upon saving it shows in the preview html section, saying the drug names do not exist. How should I proceed?

**Comment by mogoodrich** [comment]
You will most likely need to add the the drugs into your system via the admin section.  I just pinged Tobin to see if it's possible he had a working form he could test with.

**Comment by dilekamadushan** [comment]
@mogoodrich Thanks, I will first add drugs and try again. Thank you very much for the help.

**Comment by dilekamadushan** [comment]
Here is the code snippet
hidedosecode
Here is the html form created.
hidedoseview

**Comment by mogoodrich** [comment]
@dilekamadushan  did you see my comment on the HTML-329 that I made on Friday?

(Also, logging into JIRA is broken right now, so we won't be able to comment more... hopefully it will be working again soon)

**Comment by dilekamadushan** [comment]
@mogoodrich Yes I saw. I hope I haven't missed anything.

**Comment by mogoodrich** [comment]
In your screenshot, when you "hide dose", the fields for "Dosing Type" and "Dose Units" are shown, and I was suggesting in my comment that those two fields should be hidden if "hideDose='true'"

**Comment by dilekamadushan** [comment]
@mogoodrich Sorry I didn't get it earlier. I would be working on it now. Thanks

**Comment by mogoodrich** [comment]
No worres, thanks @dilekamadushan!

**Comment by dilekamadushan** [comment]
@mogoodrich  I tried out with hideDoseAndFrequency="true" with the .omod created from master branch.
screenshot from 2018-03-13 00-44-03
The result was
screenshot from 2018-03-13 00-44-27
the fields for "Dosing Type" and "Dose Units" are not missing.

**Comment by mogoodrich** [comment]
Okay, you are right to be confused... that's a bit silly that it was originally done that way, but we will go with that and keep it the way you have it.

**Comment by mogoodrich** [comment]
Merged in, thanks @dilekamadushan !

**Comment by dilekamadushan** [comment]
@mogoodrich Thank you very  for your great support

**Pull request merged**
