### PR TITLE
HTML-731: Fixed htmlFormEntry.js numbers validation.

### PR DESCRIPTION
**Pull request by shubhamsc**
https://issues.openmrs.org/browse/HTML-731

### CODE REVIEW

**Comment by shubhamsc** [comment]
@mogoodrich @mks-d Please Review

**Comment by rrameshbtech** [comment]
>I believe "val" is a string, so I fear Number.isInteger might always return false based on this line in the function docs:
> Number.isInteger('10'); // false

Yes @mogoodrich. `val` is string. So we are boxing with Number `val = Number(val);` before we do validation.

**Comment by mogoodrich** [comment]
Ah, I missed that line thanks @rrameshbtech

**Comment by rrameshbtech** [comment]
Thanks @mogoodrich. We have tested manually & ensured it is working as expected.

**Pull request merged**
